<html>
	<head>
		<title>Que es H.T.M.L.</title>
		<link href="https://fonts.googleapis.com/css2?family=Galada&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
		<link rel=StyleSheet href="css/estilos.css" type="text/css" media=screen>
	</head>
<body>
<h1 align="middle"> Que es H.T.M.L</h1>





</body>
</html>